// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function CheckRangeFormat(arg1) {
  return window['go']['main']['App']['CheckRangeFormat'](arg1);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function ConvertPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertPDF'](arg1, arg2, arg3, arg4);
}

export function DecryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2, arg3);
}

export function EncryptPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractBookmark'](arg1, arg2, arg3);
}

export function MergePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergePDF'](arg1, arg2, arg3, arg4);
}

export function OCR(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OCR'](arg1, arg2, arg3, arg4, arg5);
}

export function ReorderPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderPDF'](arg1, arg2, arg3);
}

export function RotatePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotatePDF'](arg1, arg2, arg3, arg4);
}

export function ScalePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScalePDF'](arg1, arg2, arg3, arg4);
}

export function SplitPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SplitPDF'](arg1, arg2, arg3, arg4);
}

export function TransformBookmark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransformBookmark'](arg1, arg2, arg3, arg4, arg5);
}

export function WatermarkPDF(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['WatermarkPDF'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function WriteBookmarkByFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBookmarkByFile'](arg1, arg2, arg3, arg4);
}

export function WriteBookmarkByGap(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBookmarkByGap'](arg1, arg2, arg3, arg4);
}
