// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function CheckRangeFormat(arg1) {
  return window['go']['main']['App']['CheckRangeFormat'](arg1);
}

export function CombinePDFByGrid(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CombinePDFByGrid'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function ConvertPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConvertPDF'](arg1, arg2, arg3, arg4);
}

export function CutPDFByBreakpoints(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CutPDFByBreakpoints'](arg1, arg2, arg3, arg4, arg5);
}

export function CutPDFByGrid(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CutPDFByGrid'](arg1, arg2, arg3, arg4, arg5);
}

export function DecryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2, arg3);
}

export function DeletePDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePDF'](arg1, arg2, arg3);
}

export function EncryptPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractBookmark'](arg1, arg2, arg3);
}

export function ExtractImageFromPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractImageFromPDF'](arg1, arg2, arg3);
}

export function ExtractTextFromPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractTextFromPDF'](arg1, arg2, arg3);
}

export function InsertBlankPDF(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InsertBlankPDF'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InsertPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InsertPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function MergePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergePDF'](arg1, arg2, arg3, arg4);
}

export function OCR(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OCR'](arg1, arg2, arg3, arg4, arg5);
}

export function ReorderPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderPDF'](arg1, arg2, arg3);
}

export function ReplacePDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReplacePDF'](arg1, arg2, arg3, arg4, arg5);
}

export function RotatePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotatePDF'](arg1, arg2, arg3, arg4);
}

export function ScalePDFByDim(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScalePDFByDim'](arg1, arg2, arg3, arg4, arg5);
}

export function ScalePDFByPaperSize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScalePDFByPaperSize'](arg1, arg2, arg3, arg4);
}

export function ScalePDFByScale(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScalePDFByScale'](arg1, arg2, arg3, arg4);
}

export function SplitPDFByBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByBookmark'](arg1, arg2, arg3);
}

export function SplitPDFByChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByChunk'](arg1, arg2, arg3);
}

export function SplitPDFByPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByPage'](arg1, arg2, arg3);
}

export function TransformBookmark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TransformBookmark'](arg1, arg2, arg3, arg4, arg5);
}

export function WatermarkPDF(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['WatermarkPDF'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function WriteBookmarkByFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBookmarkByFile'](arg1, arg2, arg3, arg4);
}

export function WriteBookmarkByGap(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBookmarkByGap'](arg1, arg2, arg3, arg4);
}
