// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPDFBackgroundByColor(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddPDFBackgroundByColor'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddPDFBackgroundByImage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddPDFBackgroundByImage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function AddPDFHeaderAndFooter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15) {
  return window['go']['main']['App']['AddPDFHeaderAndFooter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
}

export function AddPDFPageNumber(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['AddPDFPageNumber'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function AnnotParser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AnnotParser'](arg1, arg2, arg3, arg4, arg5);
}

export function ChangePasswordPDF(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ChangePasswordPDF'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function CheckOS() {
  return window['go']['main']['App']['CheckOS']();
}

export function CheckOutputDirExists(arg1) {
  return window['go']['main']['App']['CheckOutputDirExists'](arg1);
}

export function CheckOutputFileExists(arg1) {
  return window['go']['main']['App']['CheckOutputFileExists'](arg1);
}

export function CheckRangeFormat(arg1) {
  return window['go']['main']['App']['CheckRangeFormat'](arg1);
}

export function CheckTrialCount() {
  return window['go']['main']['App']['CheckTrialCount']();
}

export function CombinePDFByGrid(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CombinePDFByGrid'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CompressPDF(arg1, arg2) {
  return window['go']['main']['App']['CompressPDF'](arg1, arg2);
}

export function ConvertPDF2Docx(arg1, arg2) {
  return window['go']['main']['App']['ConvertPDF2Docx'](arg1, arg2);
}

export function CropPDFByBBOX(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CropPDFByBBOX'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CropPDFByMargin(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CropPDFByMargin'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CropPDFByRectAnnots(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CropPDFByRectAnnots'](arg1, arg2, arg3, arg4);
}

export function CutPDFByBreakpoints(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CutPDFByBreakpoints'](arg1, arg2, arg3, arg4, arg5);
}

export function CutPDFByGrid(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CutPDFByGrid'](arg1, arg2, arg3, arg4, arg5);
}

export function DecryptPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptPDF'](arg1, arg2, arg3);
}

export function DeletePDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePDF'](arg1, arg2, arg3);
}

export function DetectBookmarkByFont(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectBookmarkByFont'](arg1, arg2, arg3);
}

export function DetectWatermarkByIndex(arg1, arg2, arg3) {
  return window['go']['main']['App']['DetectWatermarkByIndex'](arg1, arg2, arg3);
}

export function EncryptPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EncryptPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function ExtractBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractBookmark'](arg1, arg2, arg3);
}

export function ExtractImageFromPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractImageFromPDF'](arg1, arg2, arg3);
}

export function ExtractTextFromPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractTextFromPDF'](arg1, arg2, arg3);
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function InsertBlankPDF(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['InsertBlankPDF'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function InsertPDF(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InsertPDF'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MakeDualLayerPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MakeDualLayerPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function MaskPDFByAnnot(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['MaskPDFByAnnot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function MaskPDFByRect(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['MaskPDFByRect'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function MergePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergePDF'](arg1, arg2, arg3, arg4);
}

export function OCR(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OCR'](arg1, arg2, arg3, arg4, arg5);
}

export function OCRExtract(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OCRExtract'](arg1, arg2, arg3, arg4);
}

export function OCRPDFBookmark(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OCRPDFBookmark'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}

export function PDFConversion(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['PDFConversion'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function PandocConvert(arg1, arg2, arg3) {
  return window['go']['main']['App']['PandocConvert'](arg1, arg2, arg3);
}

export function RemovePDFHeaderAndFooter(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RemovePDFHeaderAndFooter'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RemovePDFPageNumber(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RemovePDFPageNumber'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RemoveWatermark(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RemoveWatermark'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReorderPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderPDF'](arg1, arg2, arg3);
}

export function ReplacePDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReplacePDF'](arg1, arg2, arg3, arg4, arg5);
}

export function RotatePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RotatePDF'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFile() {
  return window['go']['main']['App']['SaveFile']();
}

export function ScalePDFByDim(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ScalePDFByDim'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ScalePDFByPaperSize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScalePDFByPaperSize'](arg1, arg2, arg3, arg4);
}

export function ScalePDFByScale(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScalePDFByScale'](arg1, arg2, arg3, arg4);
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function SignImage(arg1, arg2) {
  return window['go']['main']['App']['SignImage'](arg1, arg2);
}

export function SplitPDFByBookmark(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByBookmark'](arg1, arg2, arg3);
}

export function SplitPDFByChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByChunk'](arg1, arg2, arg3);
}

export function SplitPDFByPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SplitPDFByPage'](arg1, arg2, arg3);
}

export function TransformBookmark(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['TransformBookmark'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WatermarkPDFByImage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['WatermarkPDFByImage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function WatermarkPDFByPDF(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WatermarkPDFByPDF'](arg1, arg2, arg3, arg4, arg5);
}

export function WatermarkPDFByText(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16) {
  return window['go']['main']['App']['WatermarkPDFByText'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
}

export function WriteBookmarkByFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBookmarkByFile'](arg1, arg2, arg3, arg4);
}

export function WriteBookmarkByGap(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['WriteBookmarkByGap'](arg1, arg2, arg3, arg4, arg5, arg6);
}
