// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1:string):Promise<void>;

export function CompressPDF(arg1:string,arg2:string):Promise<void>;

export function ConvertPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DecryptPDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EncryptPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function ExtractBookmark(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MergePDF(arg1:Array<string>,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function OCR(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ReorderPDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RotatePDF(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ScalePDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SplitPDF(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function TransformBookmark(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:boolean):Promise<void>;

export function WatermarkPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string,arg7:number,arg8:number,arg9:number,arg10:number):Promise<void>;

export function WriteBookmarkByFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function WriteBookmarkByGap(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;
