// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompressPDF(arg1:string,arg2:string):Promise<void>;

export function ConvertPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DecryptPDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EncryptPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function MergePDF(arg1:Array<string>,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ReorderPDF(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RotatePDF(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ScalePDF(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SplitPDF(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function Test():Promise<string>;

export function WatermarkPDF(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
